# Generated by Django 4.0.2 on 2022-07-01 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=500, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='report',
            name='dateTime',
            field=models.DateTimeField(default=datetime.date(2022, 7, 1)),
        ),
        migrations.AlterField(
            model_name='report',
            name='observation',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
