# Generated by Django 4.0.2 on 2022-07-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0002_alter_item_id_alter_item_name_alter_report_datetime_and_more'),
        ('inventoryApp', '0002_alter_report_datetime_alter_report_observation'),
    ]

    operations = [
    ]
