# Generated by Django 4.0.2 on 2022-07-03 21:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0003_merge_20220703_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='name')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='report',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 21, 35, 25, 634034, tzinfo=utc)),
        ),
    ]
