# Generated by Django 4.0.2 on 2022-07-05 00:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0010_alter_report_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 17, 43, 50, 142955, tzinfo=utc)),
        ),
    ]
