# Generated by Django 4.0.2 on 2022-07-11 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0011_alter_report_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 21, 51, 44, 197645)),
        ),
        migrations.AlterField(
            model_name='report',
            name='employee',
            field=models.CharField(max_length=500),
        ),
    ]
